circuito = [
    ['teste', 'País', 'Pista', 10],
    ['Melbourne', '🇦🇺', 'Misto', 58],
    ['Shanghai', '🇨🇳', 'Desafiador', 56],
    ['Suzuka', '🇯🇵', 'Técnico', 53],
    ['Sakhir', '🇧🇭', 'Desafiador', 57],
    ['Jeddah', '🇸🇦', 'Rápido', 50],
    ['Miami', '🇺🇸', 'Misto', 57],
    ['Montreal', '🇨🇦', 'Asfalto', 70],
    ['Mônaco', '🇲🇨', 'Lento', 78],
    ['Barcelona', '🇪🇸', 'Asfalto', 66],
    ['Red Bull Ring', '🇦🇹', 'Asfalto', 71],
    ['Silverstone', '🇬🇧', 'Técnico', 52],
    ['Spa-Francorchamps', '🇧🇪', 'Asfalto', 44],
    ['Hungaroring', '🇭🇺', 'Asfalto', 70],
    ['Zandvoort', '🇳🇱', 'Asfalto', 72],
    ['Monza', '🇮🇹', 'Rápido', 53],
    ['Madrid', '🇪🇸', 'Asfalto', 57],
    ['Baku', '🇦🇿', 'Asfalto', 51],
    ['Singapura', '🇸🇬', 'Asfalto', 62],
    ['COTA', '🇺🇸', 'Asfalto', 56],
    ['Cidade do México', '🇲🇽', 'Técnico', 71],
    ['Interlagos', '🇧🇷', 'Asfalto', 58],
    ['Las Vegas', '🇺🇸', 'Urbano', 58],
    ['Catar', '🇶🇦', 'Asfalto', 57],
    ['Abu Dhabi', '🇦🇪', 'Asfalto', 58],
    ['Sochi', '🇷🇺', 'Asfalto', 58],
    ['Portimão', '🇵🇹', 'Asfalto', 58],
    ['Paul Ricard', '🇫🇷', 'Asfalto', 58],
    ]
# 'Urbano', 'Misto', 'Técnico', 'Rápido', 'Lento', 'Desafiador'